name: Create and attach tarball to Release

on:
  release:
    types: [published]

jobs:
  attach_assets:
    name: Attach Tarball
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to upload release assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      
      - name: Install npm packages
        run: |
          npm install -g npm@11.6.2

  
      # ---------- NPM INSTALL EVERY SERVICE ----------
      - name: Install npm packages
        run: |
          npm install

      # ---------- COMPILE WEB ----------
      - name: Compile web
        working-directory: ./services/web
        run: |
          npm run precompile-pug
          npm install --include=dev
          npm run webpack:production
          npm prune --omit=dev


      # ---------- PACKAGE ----------
      - name: Prepare release folder
        run: |
          mkdir -p release/
          mkdir -p release/services/
          mkdir -p release/libraries/
          
          cp -r services/* release/services/
          cp -r libraries/* release/libraries/

      # ---------- COMPRESS ----------
      - name: Compress release
        run: tar -czvf Overleaf.tar.gz release/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            overleaf.tar.gz

        
